[phases.setup]
aptPkgs = ["libgomp1"]

[phases.install]
cmds = [
    "pip install --no-cache-dir --timeout 600 catboost",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"